// export const sample_foods = [
//     {
//         id: '1',
//         name: 'Pizza Pepperoni',
//         cookTime: '10-20',
//         price: 150,
//         favorite: false,
//         origins: ['italy'],
//         stars: 4.5,
//         imageUrl: 'food-1.jpg',
//         tags: ['FastFood', 'Pizza', 'Lunch'],
//     },
//     {
//         id: '2',
//         name: 'Meatball',
//         price: 120,
//         cookTime: '20-30',
//         favorite: true,
//         origins: ['persia', 'middle east', 'china'],
//         stars: 5,
//         imageUrl: 'food-2.jpg',
//         tags: ['SlowFood', 'Lunch'],
//     },
//     {
//         id: '3',
//         name: 'Hamburger',
//         price: 80,
//         cookTime: '10-15',
//         favorite: false,
//         origins: ['germany', 'us'],
//         stars: 3.5,
//         imageUrl: 'food-3.jpg',
//         tags: ['FastFood', 'Hamburger'],
//     },
//     {
//         id: '4',
//         name: 'Fried Potatoes',
//         price: 60,
//         cookTime: '15-20',
//         favorite: true,
//         origins: ['belgium', 'france'],
//         stars: 3,
//         imageUrl: 'food-4.jpg',
//         tags: ['FastFood', 'Fry'],
//     },
//     {
//         id: '5',
//         name: 'Chicken Soup',
//         price: 70,
//         cookTime: '40-50',
//         favorite: false,
//         origins: ['india', 'asia'],
//         stars: 3.5,
//         imageUrl: 'food-5.jpg',
//         tags: ['SlowFood', 'Soup'],
//     },
//     {
//         id: '6',
//         name: 'Vegetables Pizza',
//         price: 130,
//         cookTime: '40-50',
//         favorite: false,
//         origins: ['italy'],
//         stars: 4.0,
//         imageUrl: 'food-6.jpg',
//         tags: ['FastFood', 'Pizza', 'Lunch'],
//     },
//     {
//         id: '7',
//         name: 'Butter chicken',
//         price: 260,
//         cookTime: '40-50',
//         favorite: false,
//         origins: ['India'],
//         stars: 4.0,
//         imageUrl: 'food-7.jpg',
//         tags: [' Chicken', 'curry', 'Lunch'],
//     },
//     {
//         id: '8',
//         name: 'Chicken Biryani',
//         price: 180,
//         cookTime: '40-50',
//         favorite: false,
//         origins: ['India', 'Iran'],
//         stars: 4.0,
//         imageUrl: 'food-8.jpg',
//         tags: [' Chicken', 'Rice', 'Lunch'],
//     },
// ];

// export const sample_tags = [
//     { name: 'All', count: 6 },
//     { name: 'FastFood', count: 4 },
//     { name: 'Pizza', count: 2 },
//     { name: 'Lunch', count: 4 },
//     { name: 'SlowFood', count: 2 },
//     { name: 'Hamburger', count: 1 },
//     { name: 'Fry', count: 1 },
//     { name: 'Soup', count: 1 },
//     { name: ' Chicken', count: 2 }
// ];

// export const sample_users = [
//     {
//         id: 1,
//         name: 'John Doe',
//         email: 'john@gmail.com',
//         password: '12345',
//         address: 'Toronto On',
//         isAdmin: false,
//     },
//     {
//         id: 2,
//         name: 'Jane Doe',
//         email: 'jane@gmail.com',
//         password: '12345',
//         address: 'Shanghai',
//         isAdmin: true,
//     },
// ];